{% set name = "arviz-base" %}
{% set version = "0.8.2" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arviz_base-{{ version }}.tar.gz
  sha256: 4d77142c6396c648fef3624b2d3f76fc9f326b88e513b34eff15ac06489cf840

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.4,<4
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.24
    - xarray >=2024.11.0
    - typing_extensions >=3.10

test:
  imports:
    - arviz_base
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/arviz-devs/arviz-base
  summary: Base ArviZ features and converters.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://arviz-base.readthedocs.io
  dev_url: https://github.com/arviz-devs/arviz-base


extra:
  recipe-maintainers:
    - OriolAbril
    - aloctavodia
    - tomicapretto
